Feature/new documents fields [#182009765]
bitzlato/agnessa pull request #122
Opened 2022-05-24 07:51 UTC by elnikov

2022-05-24 08:19 UTC, unloved commented on spec/factories/document_type.rb
> +    sequence(:file_type) { ['video', 'image'].sample }
sample из константы модели

2022-05-26 11:29 UTC, unloved commented on db/migrate/20220524062435_create_document_types.rb
> +      t.string :file_type
null: false

2022-05-26 11:30 UTC, unloved commented on db/migrate/20220524065820_create_verification_documents.rb
> +      t.string :file
null: false

2022-05-26 13:10 UTC, dapi commented on app/models/document_type.rb
> +    end
else?

2022-05-27 08:08 UTC, dapi commented on app/models/document_type.rb
> +    end
case flag
when '1' aa
when '2' aa
else raise "WTF flag'
end

2022-05-27 08:11 UTC, dapi commented on db/migrate/20220524062435_create_document_types.rb
> +    add_index :document_types, [:title, :account_id], unique: true
`[:account_id, :title]`

2022-05-31 09:01 UTC, unloved commented on app/models/verification.rb
> +  def validate_documents
может эту валидацию в документе делать?

2022-06-01 08:28 UTC, dapi requested changes
накоментил

2022-06-01 08:28 UTC, dapi commented on app/controllers/client/verifications_controller.rb
> +    current_account.document_types.each do |document_type|
👍 порядок

2022-06-01 08:28 UTC, dapi commented on app/views/client/verifications/_document_field.slim
> +                   hint: t('.document_hint', from: number_to_human_size(Rails.configuration.application.min_upload_file_size), to: number_to_human_size(Rails.configuration.application.max_upload_file
В helper вытащи

2022-06-01 08:28 UTC, dapi commented on app/models/verification_document.rb
> +  belongs_to :verification, required: true
`has_one :account, through: verification`

2022-06-01 08:28 UTC, dapi commented on app/models/verification_document.rb
> +
before_create

raise 'wtf' uncle account == docuemnt_type.account
``

2022-06-01 08:28 UTC, dapi commented on app/models/verification_document.rb
> +    file.filename
`delegate :file_name to: :file, prefix: true`

2022-06-01 08:28 UTC, dapi commented on app/views/admin/verifications/_documents.slim
> +      - verification.all_documents.each_with_index do |document, i|
Почему не оставить `documents`

2022-06-01 08:28 UTC, dapi commented on app/models/verification.rb
> +  def all_documents
documents

2022-06-01 08:28 UTC, dapi commented on app/models/verification.rb
> +  def all_documents
или `document_files`

2022-06-01 09:27 UTC, elnikov commented on app/models/verification_document.rb
> +    file.filename
Не получится, simple form требудет file_file_name, а у file_filename

2022-06-01 18:46 UTC, merged