Fix: Cache File in partian from js
bitzlato/agnessa pull request #169
Opened 2022-06-27 05:48 UTC by elnikov

2022-06-27 06:31 UTC, dapi commented on app/controllers/client/verifications_controller.rb
> +      verification.document_type = verification.citizenship_country&.available_documents&.first if verification.document_type.nil?
Получается что тут document_type может и не установиться (если нет страны и если нет доступных документов)

Такого не должно быть.

Всегда должен быть установлен document_type.

Надо подробнее разобрать почему не может быть страны. Такого быть не должно

2022-06-27 06:33 UTC, dapi commented on app/controllers/client/verifications_controller.rb
>        verification.citizenship_country_iso_code = Geocoder.search(request.remote_ip).first&.country if verification.citizenship_country_iso_code.nil?
Не правильно ставить страну в модели через iso_code, потому что ты как-бы залазишь во внутренности модели и нарушаешь ее абстракцию. Можешь предоставляет ассоциацию citizenship_country и все пользователи модели снаружи должны устанавливать именно ассоциацию, а не разбираться в том с каким именем ключа и в каком виде хранится этот ключ в модели.

Уважать абстракцию - один из способов программировать так, чтобы поменяв что-то где-то не отваливалось что-то где-то в другом месте.

2022-06-27 06:34 UTC, dapi commented on app/controllers/client/verifications_controller.rb
>        verification.citizenship_country_iso_code = Geocoder.search(request.remote_ip).first&.country if verification.citizenship_country_iso_code.nil?
Страна должна быть всегда. Если не смогу установить страну по IP, значит нужно установить страну по-умолчанию из настроек (Россия)

2022-06-27 06:37 UTC, dapi commented on app/helpers/verifications_helper.rb
> +    "/#{CarrierWave::Uploader::Base.cache_dir}/#{relative_path}"
1. С путями строками работать не принято потому что там могут использовать релятивные пути
2. Тут не понятно это путь в файловой системе или это путь относительно домена. Когда первый раз смотришь и когда я первый раз смотрел я был убежден что речь идет о пути в файловой системе.
3. Тебя все-таки должен инетерсновать не временный путь, а путь к тому месту где лежат кэшированные изображения. Значит и называться это хелпе должен по-другому
4. Какой смысл передавать аргументом relative_path если он просто складывается через слэш к пути?
5. Где гарантия что переключим cache_dir с uploads/tmp/ на, скажем, /tmp оно продолжает работать?

2022-06-27 06:40 UTC, dapi requested changes
Накоментил

2022-06-27 06:40 UTC, dapi commented on app/views/client/verifications/_photo_upload_script.slim
> -
Если я загружу фото и не беде наживать на сабмит оно покажется на странице?

2022-06-27 06:41 UTC, elnikov commented on app/controllers/client/verifications_controller.rb
> +      verification.document_type = verification.citizenship_country&.available_documents&.first if verification.document_type.nil?
я просто поправил инденацию тут

2022-06-27 07:07 UTC, dapi commented on app/controllers/client/verifications_controller.rb
> +      verification.document_type = verification.citizenship_country&.available_documents&.first if verification.document_type.nil?
Предусмотреть чтобы первым был паспорт

2022-06-27 07:12 UTC, dapi commented on app/controllers/client/verifications_controller.rb
>        verification.citizenship_country_iso_code = Geocoder.search(request.remote_ip).first&.country if verification.citizenship_country_iso_code.nil?
тут не должно быть поиска страны по ip. Страна должна быть уже установлена в форме

2022-06-28 07:55 UTC, dapi approved these changes

2022-06-28 07:55 UTC, merged