Render Minimal step with errors [#182475611]
bitzlato/agnessa pull request #181
Opened 2022-07-05 11:33 UTC by elnikov

2022-07-06 08:49 UTC, elnikov commented on app/controllers/client/verifications_controller.rb
> +    'verification_documents.file': 3, #TODO: что-то придумать
У файлов одинаковые аттрибуты, и нужно понять какой шаг у файла 3 или 4

попробовал определять через file_cache, это не сработает
так как file_cache не валидирует содержимое, а только присуствие файла
если файл больше 10 мб или битый, то шаг не перейдет на него в этом случае

2022-07-06 11:41 UTC, dapi commented on app/controllers/client/verifications_controller.rb
> +    errors.map { |attr, msg| VERIFICATION_ATTRS_WITH_STEP[attr] }.compact.min || 1
Вот тут помимо атрибутов смотри файлы и устанавливай минимальный шаг с их учетом

2022-07-06 11:41 UTC, dapi commented on app/controllers/client/verifications_controller.rb
> +    request.variant = params[:mobile] && browser.device.mobile? || Rails.configuration.application.always_mobile_version ? :mobile : :desktop
Это что еще за always_mobile_version ? )

2022-07-06 11:41 UTC, dapi requested changes
1

2022-07-07 06:49 UTC, dapi commented on app/controllers/client/verifications_controller.rb
> +      document.validate
??? валидация должны быть уже в модели,

2022-07-07 14:50 UTC, merged