[#181694809] Import from mongo to postgres fix
bitzlato/agnessa pull request #33
Opened 2022-04-05 05:41 UTC by elnikov

2022-04-05 11:12 UTC, dapi requested changes
откаментил

2022-04-05 11:12 UTC, dapi commented on app/models/verification.rb
> +          p e
???

2022-04-05 19:29 UTC, dapi requested changes
.

2022-04-06 08:26 UTC, elnikov commented on app/models/verification.rb
> +          p e
запустил парсинг, жду хоть какую нибду , пока не находится , но в переди часов 20 парсинга, думаю узнаю точно что может случится

2022-04-06 10:53 UTC, dapi commented on app/models/verification.rb
> +  def self.import_documents_from_mongo
Во это надо вынести отсюда в сервис который собственно занимается импортом

2022-04-06 10:55 UTC, dapi requested changes
1.  Добавь пожалуйста формирование конкретного списка заявлений которые не удалось сохранить.
2. Я думаю что каждый документ имеет смысл сохранять отдельно. Чтобы не получилось так что из-за одного документа завалился весь импорт заявки

2022-04-07 08:25 UTC, closed without merging