[#181625071] search passport number and etc
bitzlato/agnessa pull request #34
Opened 2022-04-05 05:41 UTC by elnikov

2022-04-05 11:13 UTC, dapi commented on app/controllers/admin/verifications_controller.rb
> +    Verification.where(name: verification.name).where(last_name: verification.last_name).where.not(id: verification.id)
```
where(name: verification.name, last_name: verification.last_name)
```

2022-04-05 11:14 UTC, dapi commented on app/decorators/verification_decorator.rb
> +  def dup_documents
Не должно быть

2022-04-05 11:16 UTC, dapi commented on app/views/admin/verifications/show.html.slim
>      = render 'attributes', item: verification
Паспорт: 1232131231
                 Еще _12 дублей_

2022-04-05 11:19 UTC, dapi commented on app/views/admin/verifications/show.html.slim
>      = render 'attributes', item: verification
table.table
 tr
  th Номер документа
  td
    div = verification.document_number
    - if dup_documents.any?
     p  = Есть еще заявки с 
      = link_to "таким документами #[docuemnts.count] шт", admin_verificationc_path(q: {document_number_eq: ...)
      ```

2022-04-05 11:19 UTC, dapi requested changes
правки

2022-04-05 19:29 UTC, dapi requested changes
.

2022-04-06 09:13 UTC, dapi commented on app/views/admin/verifications/_attributes.slim
> +      td class='text-right'
а зачем ты делаешь class=?
В slim-е гласы указываются через точку:
```
td.text-right
```

2022-04-06 09:13 UTC, dapi commented on app/views/admin/verifications/_attributes.slim
> +        - if dup_documents.any?
используй `ul/li`

2022-04-06 09:14 UTC, dapi requested changes
Небольшие правки

2022-04-06 09:49 UTC, elnikov commented
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/2846153/161948099-e5e1eb25-adce-48aa-8726-77e468b9e72c.png">

2022-04-06 10:52 UTC, dapi requested changes
Небольшие правки

2022-04-06 10:52 UTC, dapi commented on app/views/admin/verifications/_attributes.slim
> +        - if dup_names.any?
Промазал с отсупом

2022-04-06 10:52 UTC, dapi commented on app/views/admin/verifications/_attributes.slim
> +        - if dup_emails.any?
Промазал с отсупом )

2022-04-06 13:52 UTC, dapi commented on app/controllers/admin/verifications_controller.rb
> +                     dup_emails: dup_emails }
Кстати вообще это не `dup_`, а `similar_`

2022-04-06 13:53 UTC, dapi commented on app/views/admin/verifications/_attributes.slim
> +- item = item.decorate unless item.respond_to?(:decorated?) && item.decorated?
Непонимающ зачем это. Проще сразу передавать рекорированый и все.

2022-04-06 13:54 UTC, dapi approved these changes

2022-04-06 13:54 UTC, merged