[##181907919] add applicant_comment
bitzlato/agnessa pull request #83
Opened 2022-04-15 11:54 UTC by elnikov

2022-04-15 15:53 UTC, dapi commented
Поле должно называться user_comment. Это комментарий пользователя к заявке. То что тут речь идет об Аккаунте это частный случай

2022-04-15 15:53 UTC, dapi requested changes
Поле должно называться user_comment. Это комментарий пользователя к заявке. То что тут речь идет об Аккаунте это частный случай

2022-04-15 15:55 UTC, elnikov commented
> Поле должно называться user_comment. Это комментарий пользователя к заявке. То что тут речь идет об Аккаунте это частный случай

Ну user у нас тоже есть, и это зачастую модератор. 
Человек который пришел на форму точно не является user.
User это тот кто имеет запись в таблице user и логин и пароль.
Человек пришедший на форму - не юзер.

2022-04-15 16:05 UTC, dapi approved these changes

2022-04-15 16:06 UTC, dapi commented
Можно заребейсить и вливать

2022-04-18 10:11 UTC, dapi commented on app/models/verification.rb
> +  validate :applicant_comment_restore_info, on: :create
`validates :applicant_comment, presence: true, if: :restore?`

2022-04-18 10:12 UTC, dapi commented on app/views/admin/verifications/_header.slim
> +    .text-muted= verification.class.human_attribute_name :applicant_comment
`.mt-4`

2022-04-18 10:13 UTC, dapi requested changes
11

2022-04-18 10:52 UTC, merged