[#181956236] disable users
bitzlato/agnessa pull request #94
Opened 2022-04-25 07:20 UTC by elnikov

2022-04-25 09:15 UTC, dapi commented on app/models/member.rb
> +  def destroy
не так не надо. destroy это destroy, archive это archive

Используй https://github.com/dapi/archivable

2022-04-25 09:16 UTC, dapi requested changes
откаментил

2022-04-25 09:16 UTC, dapi commented on app/models/member.rb
> +  def destroy
Вмкесто флага используй timestamp archived_at = дата

2022-04-25 09:16 UTC, dapi commented on app/views/admin/members/index.html.slim
> +        td = link_to  admin_member_path(member),  data: { confirm: 'Are you sure?' }, method: :delete do
И соответсвенно нужна кнопка `оживить`

Архивных показывать внизу

2022-04-25 09:16 UTC, dapi commented on db/migrate/20220422110519_add_archive_to_member.rb
> +    add_column :members, :archive, :boolean, default: false
archived_at: timestamp

2022-04-25 13:25 UTC, elnikov commented on app/models/member.rb
> +  def destroy
Что-то не required это archived, наверно потому что в lib
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/2846153/165098092-edbd8843-f2fd-4691-a28d-f2c70769f361.png">

2022-04-26 08:15 UTC, dapi requested changes
archived_at

2022-04-27 08:21 UTC, merged