[#181956216] change role
bitzlato/agnessa pull request #98
Opened 2022-04-27 15:13 UTC by elnikov

2022-05-11 12:39 UTC, dapi commented on app/views/admin/members/_form.slim
> +    = f.input :role, collection: Member::ROLES
include_blank: false

2022-05-11 12:40 UTC, dapi commented on db/migrate/20220427110134_role_migration.rb
> +    change_column :members, :role, :string
`null: false, default: 'operator'`

2022-05-11 12:41 UTC, dapi requested changes
откаментил

2022-05-11 12:41 UTC, dapi commented on app/controllers/admin/members_controller.rb
> +    redirect_to admin_member_url(member), notice: 'Admin user was successfully archived.'
Восстановить и архивировать участника можно откуда угодно и из списка из со страницы частника. Поэтому возвращать нужно назад

2022-05-11 12:44 UTC, dapi commented on app/views/admin/members/index.slim
> -              i class="fa fa-trash-o"
Зачем убрал?

2022-05-11 12:47 UTC, dapi requested changes
.

2022-05-13 07:50 UTC, dapi commented on app/decorators/member_decorator.rb
> +    %i[role user archived_at]
user role

2022-05-13 07:52 UTC, dapi commented on app/models/member.rb
> -  enum role: {
`enum role: ROLES`

2022-05-13 07:53 UTC, dapi commented on app/views/admin/members/_form.slim
> +
user ?

2022-05-13 07:56 UTC, dapi commented on db/migrate/20220427110134_role_migration.rb
> +    change_column :members, :role, :string, null: false, default: 'operator'
`Member.where(role: '0').update_all role: 'operator'`

2022-05-13 07:58 UTC, dapi requested changes
откаментил

2022-05-13 07:59 UTC, dapi commented on config/locales/admin.ru.yml
> +        settings: Настройки
Убрать

2022-05-13 07:59 UTC, dapi commented on app/views/admin/members/show.slim
> += link_to "&larr; назад в пользователи".html_safe, admin_members_path
Убрать

2022-05-13 13:16 UTC, dapi commented on app/views/admin/members/index.slim
> +      tr is='dapi-tr'  data-href=url_for([:admin, member])
data-href куда ведет?

2022-05-15 16:17 UTC, unloved commented on app/decorators/member_decorator.rb
> +class MemberDecorator < ApplicationDecorator
этот класс вообще кем то используется?

2022-05-15 16:18 UTC, unloved commented on config/routes.rb
> -      resources :members, only: [:index, :show, :destroy] do
по дефолту тут будет и destroy и show, которых быть не должно, так?

2022-05-16 08:28 UTC, dapi commented on app/controllers/admin/members_controller.rb
> +    redirect_to edit_admin_member_url(member), notice: "Admin user was successfully updated."
redirect_back fallback_location: edit_admin_member_url(member)

2022-05-16 09:27 UTC, merged